name: Build Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        env:
          - couchbase_version: "3.2.2"
            php_version: "8.1"
            platforms: "linux/amd64"
            tags: "deminy/couchbase-network-check:3.2.2"
          - couchbase_version: "4.4.0"
            php_version: "8.4"
            platforms: "linux/amd64,linux/arm64/v8"
            tags: "deminy/couchbase-network-check:4.4.0,deminy/couchbase-network-check:latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish Docker Image (${{ matrix.env.couchbase_version }})
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            COUCHBASE_VERSION=${{ matrix.env.couchbase_version }}
            PHP_VERSION=${{ matrix.env.php_version }}
          platforms: ${{ matrix.env.platforms }}
          push: true
          tags: ${{ matrix.env.tags }}
