name: Build Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        couchbase_env: [{version: 3.2.2, platforms: "linux/amd64"}, {version: 4.3.0, platforms: "linux/amd64,linux/arm64/v8"}]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v5

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and Publish Docker Image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            COUCHBASE_VERSION=${{ matrix.couchbase_env.version }}
          platforms: ${{ matrix.couchbase_env.platforms }}
          push: true
          tags: deminy/couchbase-network-check:${{ matrix.couchbase_env.version }}
